# This file was generated by GoReleaser. DO NOT EDIT.
cask "laevitas" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "22254fc33752b98d188c2fe816f54a3c6d0b1cb6579c194ae3075f85cba69b1e"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
    on_arm do
      sha256 "2b9e1ebe953adac45d1f0ede4b43cd8e7ffcc696b5e76c3bc54742e3aefa0ff9"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "75c7fd01c4c7b8450eae34ab201d12002b8d799dc5a9d54d1d3b4a1685b2f1bb"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
    on_arm do
      sha256 "d8ce0d0bf90fae1bc62c08d2016bcdf77c760792dd9bfd43d8bf92fa881abe8d"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
  end

  name "laevitas"
  desc "Crypto derivatives data CLI — futures, perpetuals, options, spot, vol surfaces, prediction markets."
  homepage "https://github.com/laevitas/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "laevitas"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/laevitas")
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/laevitas"]
    end
  end

  # No zap stanza required

end
