# This file was generated by GoReleaser. DO NOT EDIT.
cask "laevitas" do
  version "0.11.3"

  on_macos do
    on_intel do
      sha256 "a154c026fc01a43b15135aa3d76cdd7cefb27d9982665826abb69d958309c3c4"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
    on_arm do
      sha256 "aa2633c33171434e13a39e3968630234656c655c690798dc493726e3a795454b"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d4bb390dd44f53b712b844a00ed08a8355c61563e70e6ea5062fa1873cc6071"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
    on_arm do
      sha256 "afc3d24d2584c237b1f35e44e3e9e6608c7d9ca21fef37456aaf2545d39cafc1"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
  end

  name "laevitas"
  desc "Crypto derivatives data CLI — futures, perpetuals, options, spot, vol surfaces, prediction markets."
  homepage "https://github.com/laevitas/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "laevitas"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/laevitas")
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/laevitas"]
    end
  end

  # No zap stanza required

end
