# This file was generated by GoReleaser. DO NOT EDIT.
cask "laevitas" do
  version "0.8.2"

  on_macos do
    on_intel do
      sha256 "cfab09aa07b5f37039dd9badc521555c2bb3d09740f0d76700a84ac87a26fc4b"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
    on_arm do
      sha256 "e17b8e7475bf0802b2a1a0f1811cdcf92b6a7354bc641eb9e6ce7d200a151c5d"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0c0090cb691ab748869dcd4771320eb4fef4597f29b4944344698696d8fbb15"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
    on_arm do
      sha256 "e9b7a6bb9d75ae763a9d981f2cd61acd9a090acebaac2da1199edee8c5aadfb5"
      url "https://github.com/laevitas/cli/releases/download/v#{version}/laevitas_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/laevitas/cli"
    end
  end

  name "laevitas"
  desc "Crypto derivatives data CLI — futures, perpetuals, options, spot, vol surfaces, prediction markets."
  homepage "https://github.com/laevitas/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "laevitas"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/laevitas")
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/laevitas"]
    end
  end

  # No zap stanza required

end
